apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-321
  name: api-tester-3211
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-3211
    version: 3.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: backend-server
      name: api-tester
      instance: api-tester-3211
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-anotherclass
        component: backend-server
        name: api-tester
        instance: api-tester-3211
        version: 3.0.0
    spec:
      serviceAccountName: api-tester-3211
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: api-tester-3211
          # 1pro는 본인의 dockerhub username으로 변경해 주세요.
          image: zaimyon/api-tester:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: api-tester-3211-properties
          env:
            - name: downward_env_pod-name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: downward_env_node-name
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: downward_env_pod-ip
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
            - name: downward-api-pod-info
              mountPath: /usr/src/myapp/downward-api
      volumes:
        - name: secret-datasource
          secret:
            secretName: api-tester-3211-postgresql
        - name: downward-api-pod-info
          downwardAPI:
            items:
              - path: "metadata_labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "metadata_annotations"
                fieldRef:
                  fieldPath: metadata.annotations
